### ISSUE TITLE
PsiInvalidElementAccessException

### ISSUE THREAD

**Issue by sxhya** [JetBrains/intellij-arend#164]
````
com.intellij.psi.PsiInvalidElementAccessException: Element: class org.arend.psi.impl.ArendCoClauseImpl #Arend  because: containing file is null
invalidated at: see attachment
	at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:482)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.ensureValid(SmartPointerManagerImpl.java:96)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:69)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:62)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:57)
	at com.intellij.psi.SmartPointerManager.createPointer(SmartPointerManager.java:31)
	at org.arend.highlight.BasePass.reportToEditor(BasePass.kt:143)
	at org.arend.highlight.TypecheckerPass.collectInformationWithProgress(TypecheckerPass.kt:20)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)`

**Comment by sxhya** [comment]
`com.intellij.psi.PsiInvalidElementAccessException: Element: class org.arend.psi.impl.ArendGoalImpl #Arend  because: containing file is null
invalidated at: see attachment
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getManager(ASTDelegatePsiElement.java:76)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getManager(ASTDelegatePsiElement.java:53)
	at com.intellij.psi.impl.PsiElementBase.getProject(PsiElementBase.java:214)
	at org.arend.psi.ext.ArendCompositeElementKt.positionTextRepresentationImpl(ArendCompositeElement.kt:30)
	at org.arend.psi.ext.ArendCompositeElementImpl$positionTextRepresentation$$inlined$runReadAction$1.compute(actions.kt:79)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:807)
	at org.arend.psi.ext.ArendCompositeElementImpl.positionTextRepresentation(ArendCompositeElement.kt:132)
	at org.arend.ext.error.SourceInfoReference.getRefName(SourceInfoReference.java:33)
	at org.arend.ext.prettyprinting.doc.ReferenceDoc.isEmpty(ReferenceDoc.java:29)
	at org.arend.ext.prettyprinting.doc.DocFactory.hEnd(DocFactory.java:143)
	at org.arend.ext.prettyprinting.doc.DocFactory.hEnd(DocFactory.java:156)
	at org.arend.ext.error.GeneralError.getHeaderDoc(GeneralError.java:64)
	at org.arend.injection.InjectedArendEditor$updateErrorText$$inlined$runReadAction$1.compute(actions.kt:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:807)
	at org.arend.injection.InjectedArendEditor.updateErrorText(InjectedArendEditor.kt:118)
	at org.arend.injection.InjectedArendEditor.<init>(InjectedArendEditor.kt:64)
	at org.arend.toolWindow.errors.ArendMessagesView$setActiveEditor$arendEditor$1.apply(ArendMessagesView.kt:107)
	at org.arend.toolWindow.errors.ArendMessagesView$setActiveEditor$arendEditor$1.apply(ArendMessagesView.kt:34)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at org.arend.toolWindow.errors.ArendMessagesView.setActiveEditor(ArendMessagesView.kt:105)
	at org.arend.toolWindow.errors.ArendMessagesView.valueChanged(ArendMessagesView.kt:98)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:2967)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3456)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:621)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:297)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:191)
	at org.arend.toolWindow.errors.tree.ArendErrorTree.selectNode(ArendErrorTree.kt:63)
	at org.arend.toolWindow.errors.tree.ArendErrorTree.select(ArendErrorTree.kt:48)
	at org.arend.toolWindow.errors.tree.ArendErrorTreeAutoScrollFromSource.selectElementFromEditor(ArendErrorTreeAutoScrollFromSource.kt:99)
	at org.arend.toolWindow.errors.tree.ArendErrorTreeAutoScrollFromSource.access$selectElementFromEditor(ArendErrorTreeAutoScrollFromSource.kt:35)
	at org.arend.toolWindow.errors.tree.ArendErrorTreeAutoScrollFromSource$selectInAlarm$1.run(ArendErrorTreeAutoScrollFromSource.kt:65)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:371)
	at com.intellij.util.Alarm$Request.run(Alarm.java:358)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:217)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by ice1000** [comment]
```
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type DEF_CLASS (class org.arend.psi.stubs.ArendDefClassStub$Type)
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:79)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:101)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:253)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.isPhysical(StubBasedPsiElementBase.java:296)
	at com.intellij.psi.util.PsiTreeUtil.processElements(PsiTreeUtil.java:871)
	at com.intellij.psi.util.PsiTreeUtil.findChildOfType(PsiTreeUtil.java:249)
	at com.intellij.psi.util.PsiTreeUtil.findChildOfType(PsiTreeUtil.java:220)
	at org.arend.psi.ext.PsiStubbedReferableImpl.getName(PsiReferable.kt:75)
	at org.arend.psi.ext.PsiStubbedReferableImpl.textRepresentation(PsiReferable.kt:58)
	at org.arend.psi.ext.PsiLocatedReferableKt.getFullName(PsiLocatedReferable.kt:31)
	at org.arend.psi.ext.PsiLocatedReferableKt.getFullName(PsiLocatedReferable.kt:37)
	at org.arend.typechecking.execution.TypeCheckRunLineMarkerContributor$getInfo$1.fun(TypeCheckRunLineMarkerContributor.kt:39)
	at org.arend.typechecking.execution.TypeCheckRunLineMarkerContributor$getInfo$1.fun(TypeCheckRunLineMarkerContributor.kt:16)
	at com.intellij.execution.lineMarker.RunLineMarkerContributor$Info.lambda$new$0(RunLineMarkerContributor.java:47)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.lambda$getLineMarkerInfo$1(RunLineMarkerProvider.java:95)
	at com.intellij.codeInsight.daemon.LineMarkerInfo.getLineMarkerTooltip(LineMarkerInfo.java:147)
	at com.intellij.codeInsight.daemon.LineMarkerInfo$LineMarkerGutterIconRenderer.getTooltipText(LineMarkerInfo.java:200)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl$2.lambda$run$0(EditorGutterComponentImpl.java:1717)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:899)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl$2.run(EditorGutterComponentImpl.java:1717)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:930)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:432)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
