### ISSUE TITLE
Mysterious NPE

### ISSUE THREAD

**Issue by ice1000** [JetBrains/intellij-arend#179]
Happened when I open arend-lib. Not sure if I can reproduce, but the stacktrace says something.

```
java.lang.NullPointerException
	at org.arend.naming.scope.ConvertingScope.find(ConvertingScope.java:43)
	at org.arend.naming.scope.CachingScope.<init>(CachingScope.java:24)
	at org.arend.naming.scope.CachingScope.make(CachingScope.java:33)
	at org.arend.injection.InjectedArendEditor$updateErrorText$$inlined$runReadAction$1.compute(actions.kt:86)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:880)
	at org.arend.injection.InjectedArendEditor.updateErrorText(InjectedArendEditor.kt:133)
	at org.arend.injection.InjectedArendEditor.<init>(InjectedArendEditor.kt:70)
	at org.arend.toolWindow.errors.ArendMessagesView$setActiveEditor$arendEditor$1.apply(ArendMessagesView.kt:107)
	at org.arend.toolWindow.errors.ArendMessagesView$setActiveEditor$arendEditor$1.apply(ArendMessagesView.kt:34)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at org.arend.toolWindow.errors.ArendMessagesView.setActiveEditor(ArendMessagesView.kt:105)
	at org.arend.toolWindow.errors.ArendMessagesView.valueChanged(ArendMessagesView.kt:98)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:2967)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3456)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:623)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:297)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:191)
	at org.arend.toolWindow.errors.tree.ArendErrorTree.selectNode(ArendErrorTree.kt:63)
	at org.arend.toolWindow.errors.tree.ArendErrorTree.selectFirst(ArendErrorTree.kt:50)
	at org.arend.toolWindow.errors.ArendMessagesService$activate$$inlined$runInEdt$lambda$1.run(ArendMessagesService.kt:22)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$activateToolWindow$1.run(ToolWindowManagerImpl.kt:556)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by ice1000** [comment]
It occurs when the `extensionsDir` is invalid. Maybe we need better error handling.

**Comment by valis** [comment]
Fixed
