### ISSUE TITLE
PsiInvalidElementAccessException

### ISSUE THREAD

**Issue by valis** [JetBrains/intellij-arend#190]
```
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type DEF_FUNCTION (class org.arend.psi.stubs.ArendDefFunctionStub$Type)
	at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:79)
	at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:101)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:253)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.isPhysical(StubBasedPsiElementBase.java:296)
	at com.intellij.psi.impl.PsiElementBase.isPhysical(PsiElementBase.java:242)
	at com.intellij.psi.impl.PsiElementBase.isPhysical(PsiElementBase.java:242)
	at com.intellij.psi.impl.PsiElementBase.isPhysical(PsiElementBase.java:242)
	at com.intellij.psi.impl.PsiElementBase.isPhysical(PsiElementBase.java:242)
	at com.intellij.psi.impl.PsiElementBase.isPhysical(PsiElementBase.java:242)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:159)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:235)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:117)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:75)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:73)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:154)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at org.arend.quickfix.referenceResolve.ArendImportHintAction$Companion.doComputeAvailability(ArendImportHintAction.kt:124)
	at org.arend.quickfix.referenceResolve.ArendImportHintAction$Companion.access$doComputeAvailability(ArendImportHintAction.kt:120)
	at org.arend.quickfix.referenceResolve.ArendImportHintAction.checkAvailability(ArendImportHintAction.kt:55)
	at org.arend.quickfix.referenceResolve.ArendImportHintAction.isAvailable(ArendImportHintAction.kt:51)
	at com.intellij.codeInsight.daemon.impl.ShowAutoImportPass.importUnambiguousImports(ShowAutoImportPass.java:106)
	at com.intellij.codeInsight.daemon.impl.ShowAutoImportPass.showImports(ShowAutoImportPass.java:78)
	at com.intellij.openapi.application.constraints.ConstrainedTaskExecutor.lambda$submit$1(ConstrainedTaskExecutor.java:41)
	at com.intellij.openapi.application.constraints.ConstrainedTaskExecutor.lambda$submit$4(ConstrainedTaskExecutor.java:64)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$scheduleWithinConstraints$1.invoke(BaseConstrainedExecution.kt:54)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$scheduleWithinConstraints$1$inner$$inlined$Runnable$1.run(Runnable.kt:21)
	at com.intellij.openapi.application.impl.AppUIExecutorImpl$later$1$schedule$1.run(AppUIExecutorImpl.kt:107)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLaterOnWriteThread$11(ApplicationImpl.java:806)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by sxhya** [comment]
Can't reproduce
