### ISSUE TITLE
PsiInvalidElementAccessException

### ISSUE THREAD

**Issue by ice1000** [JetBrains/intellij-arend#239]
```
2020-10-03 09:37:43,806 [ 187489]  ERROR - aemon.impl.PassExecutorService - Plugin to blame: Arend version: 1.4.1
2020-10-03 09:37:43,806 [ 187489]  ERROR - aemon.impl.PassExecutorService - Last Action: EditorBackSpace
2020-10-03 09:37:43,806 [ 187489]  ERROR - aemon.impl.PassExecutorService - Element: class org.arend.psi.impl.ArendDefIdentifierImpl #Arend  because: containing file is null
invalidated at: see attachment [Plugin: org.arend.lang]
com.intellij.diagnostic.PluginException: Element: class org.arend.psi.impl.ArendDefIdentifierImpl #Arend  because: containing file is null
invalidated at: see attachment [Plugin: org.arend.lang]
        at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:290)
        at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
        at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:67)
        at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:478)
        at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.ensureValid(SmartPointerManagerImpl.java:107)
        at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:80)
        at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:73)
        at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:68)
        at com.intellij.psi.SmartPointerManager.createPointer(SmartPointerManager.java:31)
        at com.intellij.model.psi.impl.Psi2Symbol$MyPointer.<init>(Psi2Symbol.java:41)
        at com.intellij.model.psi.impl.Psi2Symbol$MyPointer.<init>(Psi2Symbol.java:36)
        at com.intellij.model.psi.impl.Psi2Symbol.<init>(Psi2Symbol.java:17)
        at com.intellij.model.psi.impl.PsiSymbolServiceImpl.asSymbol(PsiSymbolServiceImpl.java:19)
        at com.intellij.model.psi.impl.TargetData$Evaluator.getTargets(classes.kt:44)
        at com.intellij.model.psi.impl.TargetsKt.targetSymbols(targets.kt:28)
        at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getTargetSymbols(IdentifierHighlighterPass.java:247)
        at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightReferencesAndDeclarations(IdentifierHighlighterPass.java:225)
        at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:90)
        at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
        at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
        at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
        at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.intellij.psi.PsiInvalidElementAccessException: Element: class org.arend.psi.impl.ArendDefIdentifierImpl #Arend  because: containing file is null
invalidated at: see attachment
        ... 33 more
```

The stacktrace is not helpful at all. It hides everything.

**Comment by sxhya** [comment]
Can't reproduce
