### ISSUE TITLE
Mark file as plain text leads to IDE Freeze

### ISSUE THREAD

**Issue by sxhya** [JetBrains/intellij-arend#273]
Mark a file in arend-lib (for instance Algebra.Group) as plain text. You will get IDE freeze + exception

```
com.intellij.diagnostic.Freeze
	at org.arend.typechecking.order.Ordering.forDependencies(Ordering.java:128)
	at org.arend.typechecking.order.Ordering.forDependencies(Ordering.java:24)
	at org.arend.typechecking.order.BellmanFord.doOrderRecursively(BellmanFord.java:34)
	at org.arend.typechecking.order.BellmanFord.lambda$doOrderRecursively$0(BellmanFord.java:37)
	at org.arend.typechecking.order.BellmanFord$$Lambda$2892/0x0000000101e9f040.accept(Unknown Source)
	at org.arend.typechecking.order.Ordering.forDependencies(Ordering.java:171)
	at org.arend.typechecking.order.Ordering.forDependencies(Ordering.java:24)
	at org.arend.typechecking.order.BellmanFord.doOrderRecursively(BellmanFord.java:34)
	at org.arend.typechecking.order.BellmanFord.lambda$doOrderRecursively$0(BellmanFord.java:37)
	at org.arend.typechecking.order.BellmanFord$$Lambda$2892/0x0000000101e9f040.accept(Unknown Source)
	at org.arend.typechecking.order.Ordering.forDependencies(Ordering.java:128)
	at org.arend.typechecking.order.Ordering.forDependencies(Ordering.java:24)
	at org.arend.typechecking.order.BellmanFord.doOrderRecursively(BellmanFord.java:34)
	at org.arend.typechecking.order.BellmanFord.order(BellmanFord.java:24)
	at org.arend.typechecking.order.Ordering.order(Ordering.java:113)
	at org.arend.typechecking.order.listener.TypecheckingOrderingListener.lambda$typecheckDefinitions$0(TypecheckingOrderingListener.java:101)
	at org.arend.typechecking.order.listener.TypecheckingOrderingListener$$Lambda$2991/0x0000000101fbfc40.get(Unknown Source)
	at org.arend.typechecking.computation.ComputationRunner.run(ComputationRunner.java:48)
	at org.arend.typechecking.computation.BooleanComputationRunner.run(BooleanComputationRunner.java:8)
	at org.arend.typechecking.order.listener.TypecheckingOrderingListener.typecheckDefinitions(TypecheckingOrderingListener.java:98)
	at org.arend.extImpl.ArendDependencyProviderImpl.getDefinition(ArendDependencyProviderImpl.java:41)
	at org.arend.extImpl.ArendDependencyProviderImpl.load(ArendDependencyProviderImpl.java:66)
	at org.arend.lib.StdExtension.load(StdExtension.java:104)
	at org.arend.library.SourceLibrary.load(SourceLibrary.java:293)
	at org.arend.library.LibraryManager.loadLibrary(LibraryManager.java:224)
	at org.arend.util.ProjectUtilsKt$register$$inlined$runReadAction$1.compute(actions.kt:61)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:830)
	at org.arend.util.ProjectUtilsKt.register(ProjectUtils.kt:62)
	at org.arend.ArendStartupActivity.runActivity(ArendStartupActivity.kt:46)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.java:335)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:309)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivities$3(StartupManagerImpl.java:245)
	at com.intellij.ide.startup.impl.StartupManagerImpl$$Lambda$1867/0x00000001015c4040.run(Unknown Source)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:403)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:395)
	at com.intellij.openapi.project.DumbServiceImpl$$Lambda$2788/0x0000000101d3e440.run(Unknown Source)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.ApplicationImpl$$Lambda$283/0x000000010046d440.run(Unknown Source)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop@11.0.10/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop@11.0.10/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop@11.0.10/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop@11.0.10/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base@11.0.10/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.10/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop@11.0.10/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.ide.IdeEventQueue$$Lambda$339/0x0000000100598c40.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.ide.IdeEventQueue$$Lambda$337/0x0000000100550840.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)```

**Comment by sxhya** [comment]
Can't reproduce
