### ISSUE TITLE
Typechecking all modules in a library leads to exceptions

### ISSUE THREAD

**Issue by marat-rkh** [JetBrains/intellij-arend#301]
Reproduced in Arend 1.7
1. Create new project Test1 with 2 files:
```tex
-- Test1/src/A.ard
\func foo => {?}
```
```tex
-- Test1/src/B.ard
\func foo : Nat => Nat
```
2. Create an "Arend Typecheck" run configuration with "Arend library" set to "Test1" and leave other fields empty.
3. Run that configuration.

IDE shows me 2 exceptions. Run window doesn't show typechecking results.

<img width="1106" alt="Screen Shot 2021-09-07 at 6 26 53 PM" src="https://user-images.githubusercontent.com/5653229/132371180-724ff9b4-907c-4327-8d63-a6e4ce9993e4.png">

```
java.lang.NullPointerException
	at org.arend.typechecking.error.TypecheckingErrorReporter$DocConsolePrinter$print$$inlined$runReadAction$1.compute(actions.kt:61)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at org.arend.typechecking.error.TypecheckingErrorReporter$DocConsolePrinter.print(TypecheckingErrorReporter.kt:147)
	at org.arend.typechecking.error.TypecheckingErrorReporter$ErrorProxyAction.runAction(TypecheckingErrorReporter.kt:64)
	at org.arend.typechecking.execution.TypecheckingEventsProcessor.executeProxyAction(TypecheckingEventsProcessor.kt:227)
	at org.arend.typechecking.error.TypecheckingErrorReporter$flush$lambda-2$$inlined$runReadAction$1.compute(actions.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at org.arend.typechecking.error.TypecheckingErrorReporter.flush$lambda-2(TypecheckingErrorReporter.kt:147)
	at org.arend.ext.error.GeneralError.forAffectedDefinitions(GeneralError.java:103)
	at org.arend.typechecking.error.TypecheckingErrorReporter.flush(TypecheckingErrorReporter.kt:42)
	at org.arend.typechecking.execution.TypeCheckProcessHandler.startNotify$lambda-3(TypeCheckProcessHandler.kt:188)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
```
com.intellij.diagnostic.PluginException: Element: class org.arend.psi.impl.ArendDefFunctionImpl #Arend  because: different providers: com.intellij.psi.SingleRootFileViewProvider{vFile=file:///Users/Marat.Khabibullin/Projects/Arend/TestProjects/Test1/src/A.ard, vFileId=59930, content=VirtualFileContent{size=16}, eventSystemEnabled=true}(497345cf); com.intellij.psi.SingleRootFileViewProvider{vFile=file:///Users/Marat.Khabibullin/Projects/Arend/TestProjects/Test1/src/A.ard, vFileId=59930, content=VirtualFileContent{size=16}, eventSystemEnabled=true}(7d1c56be)
invalidated at: see attachment [Plugin: org.arend.lang]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:274)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:100)
	at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:476)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.ensureValid(SmartPointerManagerImpl.java:108)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:81)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.createSmartPsiElementPointer(SmartPointerManagerImpl.java:74)
	at org.arend.typechecking.execution.DefinitionProxy.<init>(DefinitionProxy.kt:24)
	at org.arend.typechecking.execution.TypecheckingEventsProcessor.onTestStarted$lambda-9(TypecheckingEventsProcessor.kt:153)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.intellij.psi.PsiInvalidElementAccessException: Element: class org.arend.psi.impl.ArendDefFunctionImpl #Arend  because: different providers: com.intellij.psi.SingleRootFileViewProvider{vFile=file:///Users/Marat.Khabibullin/Projects/Arend/TestProjects/Test1/src/A.ard, vFileId=59930, content=VirtualFileContent{size=16}, eventSystemEnabled=true}(497345cf); com.intellij.psi.SingleRootFileViewProvider{vFile=file:///Users/Marat.Khabibullin/Projects/Arend/TestProjects/Test1/src/A.ard, vFileId=59930, content=VirtualFileContent{size=16}, eventSystemEnabled=true}(7d1c56be)
invalidated at: see attachment
	... 33 more
```

**Comment by valis** [comment]
Can you check if this error is still present? I cannot reproduce it.

**Comment by marat-rkh** [comment]
Indeed, I cannot reproduce neither in 2021.3.1 nor in master. Closing...
