### ISSUE TITLE
Thread issue

### ISSUE THREAD

**Issue by ice1000** [JetBrains/intellij-arend#380]
```
java.lang.Throwable: 'psi.File' is requested on EDT by SmartSelect#update@keyboard shortcut (com.intellij.ide.actions.SmartSelect). See ActionUpdateThread javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.reportValueProvidedByRulesUsage(PreCachedDataContext.java:245)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.getDataInner(PreCachedDataContext.java:209)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.getData(PreCachedDataContext.java:162)
	at org.arend.actions.ArendSmartSelectProvider.getSource(ArendSmartSelectProvider.kt:80)
	at org.arend.actions.ArendSmartSelectProvider.getSource(ArendSmartSelectProvider.kt:19)
	at com.intellij.openapi.ide.SmartSelectProvider.isEnabled(SmartSelectProvider.java:33)
	at com.intellij.ide.actions.SmartSelect.getProvider(SmartSelect.java:63)
	at com.intellij.ide.actions.SmartSelect.update(SmartSelect.java:44)
```

**Comment by knisht** [comment]
Wow, the platform is so thoughtful about the plugins.
