### ISSUE TITLE
java.lang.Throwable: Invalid definition of XXX in caches

### ISSUE THREAD

**Issue by sxhya** [JetBrains/intellij-arend#385]
To reproduce open e.g. `Paths` from standard library in Intellij.
Type any inline comment (e.g. `{-1-}`) before `: \Type` in the first telescope.

```
 It does not do any harm generally, but there may be some incorrect red code in the editor.
 Please try to find a stable reproducer for this behavior and report it to maintainers.
 Typical reproduction actions involve deleting some parts of text or clearing and re-inserting the whole file.
java.lang.Throwable:  Invalid definition idpe in caches. 
 It does not do any harm generally, but there may be some incorrect red code in the editor.
 Please try to find a stable reproducer for this behavior and report it to maintainers.
 Typical reproduction actions involve deleting some parts of text or clearing and re-inserting the whole file.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at org.arend.psi.ArendFile$LifetimeAwareDefinitionRegistry.get(ArendFile.kt:92)
	at org.arend.psi.ArendFile$LifetimeAwareDefinitionRegistry.get(ArendFile.kt:88)
	at org.arend.psi.ext.ReferableBase$special$$inlined$runReadAction$1.compute(actions.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:860)
	at org.arend.psi.ext.ReferableBase.getTcReferable(ReferableBase.kt:163)
	at org.arend.psi.ext.ArendFunctionDefinition.getTcReferable(ArendFunctionDefinition.kt:25)
	at org.arend.typechecking.execution.TypeCheckRunLineMarkerContributor.getInfo(TypeCheckRunLineMarkerContributor.kt:25)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:63)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:184)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:99)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:397)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:396)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:372)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:370)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by ice1000** [comment]
🔮
