### ISSUE TITLE
NPE in LevelEquations

### ISSUE THREAD

**Issue by sxhya** [JetBrains/intellij-arend#386]
To reproduce:

1. Open `Algebra.Ordered` from arend-lib in IDE 
2. Find `inv-positive` lemma
3. In the argument `Inv {\this}` position caret before first brace
4. Erase the first (opening) brace (with Backspace) and write `(`, wait for a couple of secs
5. Replace the closing brace with `)`, wait for a couple of secs
6. Now in `Inv (\this)` replace the first parenthesis with `{`, the closing parenthesis will also get replaced by a closing brace
7. Exception appears

```
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at org.arend.typechecking.implicitargs.equations.LevelEquations.solve(LevelEquations.java:62)
	at org.arend.typechecking.implicitargs.equations.LevelEquationsSolver.solveLevels(LevelEquationsSolver.java:255)
	at org.arend.typechecking.visitor.CheckTypeVisitor.finalCheckType(CheckTypeVisitor.java:1119)
	at org.arend.typechecking.visitor.DefinitionTypechecker.typecheckClassField(DefinitionTypechecker.java:3203)
	at org.arend.typechecking.visitor.DefinitionTypechecker.typecheckClass(DefinitionTypechecker.java:2801)
	at org.arend.typechecking.visitor.DefinitionTypechecker.visitClass(DefinitionTypechecker.java:223)
	at org.arend.typechecking.visitor.DefinitionTypechecker.visitClass(DefinitionTypechecker.java:67)
	at org.arend.term.concrete.Concrete$ClassDefinition.accept(Concrete.java:2156)
	at org.arend.typechecking.order.listener.TypecheckingOrderingListener.unitFound(TypecheckingOrderingListener.java:238)
	at org.arend.typechecking.order.listener.CollectingOrderingListener$MyUnit.feedTo(CollectingOrderingListener.java:52)
	at org.arend.typechecking.BackgroundTypechecker$typecheckDefinition$ok$1.invoke$lambda$1(BackgroundTypechecker.kt:95)
	at org.arend.typechecking.computation.ComputationRunner.run(ComputationRunner.java:48)
	at org.arend.typechecking.computation.BooleanComputationRunner.run(BooleanComputationRunner.java:8)
	at org.arend.typechecking.BackgroundTypechecker$typecheckDefinition$ok$1.invoke(BackgroundTypechecker.kt:93)
	at org.arend.typechecking.BackgroundTypechecker$typecheckDefinition$ok$1.invoke(BackgroundTypechecker.kt:92)
	at org.arend.typechecking.DefinitionBlacklistService.runTimed(DefinitionBlacklistService.kt:24)
	at org.arend.typechecking.BackgroundTypechecker.typecheckDefinition(BackgroundTypechecker.kt:92)
	at org.arend.typechecking.BackgroundTypechecker.access$typecheckDefinition(BackgroundTypechecker.kt:23)
	at org.arend.typechecking.BackgroundTypechecker$runTypechecker$2.run(BackgroundTypechecker.kt:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:425)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:476)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-02-14 19:08:14,850 [  40331] SEVERE - #c.i.o.p.Task - IntelliJ IDEA 2022.3  Build #IC-223.7571.182
2023-02-14 19:08:14,850 [  40331] SEVERE - #c.i.o.p.Task - JDK: 17.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-02-14 19:08:14,850 [  40331] SEVERE - #c.i.o.p.Task - OS: Linux
2023-02-14 19:08:14,851 [  40332] SEVERE - #c.i.o.p.Task - Plugin to blame: Arend version: 1.9.0.1
```

**Comment by valis** [comment]
Fixed in [39db0065](https://github.com/JetBrains/Arend/commit/39db0065af560f6c48300fc85116ec5b1476b4b2).
