### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by sxhya** [JetBrains/intellij-arend#416]
```
java.lang.StackOverflowError
	at com.intellij.openapi.progress.Cancellation.currentJob(Cancellation.java:26)
	at com.intellij.openapi.progress.Cancellation.checkCancelled(Cancellation.java:35)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:133)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:231)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:676)
	at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:15)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getParent(SharedImplUtil.java:33)
	at com.intellij.extapi.psi.ASTWrapperPsiElement.getParent(ASTWrapperPsiElement.java:19)
	at org.arend.psi.ext.ArendCompositeElementKt.getTopmostEquivalentSourceNode(ArendCompositeElement.kt:88)
	at org.arend.psi.ext.ArendSourceNodeImpl.getTopmostEquivalentSourceNode(ArendCompositeElement.kt:123)
	at org.arend.psi.ext.ArendCompositeElementKt.getParentSourceNode(ArendCompositeElement.kt:109)
	at org.arend.psi.ext.ArendSourceNodeImpl.getParentSourceNode(ArendCompositeElement.kt:125)
	at org.arend.psi.ext.ArendSourceNodeImpl.getParentSourceNode(ArendCompositeElement.kt:122)
	at org.arend.naming.scope.ScopeFactory.forSourceNode(ScopeFactory.java:133)
	at org.arend.psi.ext.ArendCompositeElementKt.getArendScope(ArendCompositeElement.kt:63)
	at org.arend.psi.ext.ArendCompositeElementImpl.getScope(ArendCompositeElement.kt:113)
	at org.arend.resolving.ArendReferenceBase$resolve$resolver$1.invoke(ArendReference.kt:74)
	at org.arend.resolving.ArendReferenceBase$resolve$resolver$1.invoke(ArendReference.kt:47)
	at org.arend.resolving.ArendResolveCache.resolveCached(ArendResolveCache.kt:44)
	at org.arend.resolving.ArendReferenceBase.resolve(ArendReference.kt:79)
	at org.arend.psi.ext.ArendDefClass.getSuperClassReferences(ArendDefClass.kt:55)
	at org.arend.naming.scope.ClassFieldImplScope.find(ClassFieldImplScope.java:76)
	at org.arend.naming.scope.Scope.resolveName(Scope.java:51)
	at org.arend.naming.scope.Scope.resolveName(Scope.java:56)
	at org.arend.naming.scope.LexicalScope.resolveInternal(LexicalScope.java:191)
	at org.arend.naming.scope.LexicalScope.resolve(LexicalScope.java:271)
	at org.arend.naming.scope.LexicalScope.resolveName(LexicalScope.java:323)
	at org.arend.naming.scope.LexicalScope.resolve(LexicalScope.java:317)
	at org.arend.naming.scope.LexicalScope.resolveName(LexicalScope.java:323)
	at org.arend.psi.ext.ArendCompositeElementKt$getArendScope$2.resolveName(ArendCompositeElement.kt:73)
	at org.arend.resolving.ArendReferenceBase$resolve$resolver$1.invoke(ArendReference.kt:74)
	at org.arend.resolving.ArendReferenceBase$resolve$resolver$1.invoke(ArendReference.kt:47)
	at org.arend.resolving.ArendResolveCache.resolveCached(ArendResolveCache.kt:44)
	at org.arend.resolving.ArendReferenceBase.resolve(ArendReference.kt:79)
	at org.arend.psi.ext.ArendDefClass.getSuperClassReferences(ArendDefClass.kt:55)
	at org.arend.naming.scope.ClassFieldImplScope.find(ClassFieldImplScope.java:76)
	at org.arend.naming.scope.Scope.resolveName(Scope.java:51)
	at org.arend.naming.scope.Scope.resolveName(Scope.java:56)
	at org.arend.naming.scope.LexicalScope.resolveInternal(LexicalScope.java:191)
	at org.arend.naming.scope.LexicalScope.resolve(LexicalScope.java:271)
	at org.arend.naming.scope.LexicalScope.resolveName(LexicalScope.java:323)
	at org.arend.naming.scope.LexicalScope.resolve(LexicalScope.java:317)
	at org.arend.naming.scope.LexicalScope.resolveName(LexicalScope.java:323)
	at org.arend.psi.ext.ArendCompositeElementKt$getArendScope$2.resolveName(ArendCompositeElement.kt:73)
	at org.arend.resolving.ArendReferenceBase$resolve$resolver$1.invoke(ArendReference.kt:74)
	at org.arend.resolving.ArendReferenceBase$resolve$resolver$1.invoke(ArendReference.kt:47)
	at org.arend.resolving.ArendResolveCache.resolveCached(ArendResolveCache.kt:44)
	at org.arend.resolving.ArendReferenceBase.resolve(ArendReference.kt:79)
	at org.arend.psi.ext.ArendDefClass.getSuperClassReferences(ArendDefClass.kt:55)
	at org.arend.naming.scope.ClassFieldImplScope.find(ClassFieldImplScope.java:76)
	at org.arend.naming.scope.Scope.resolveName(Scope.java:51)
	at org.arend.naming.scope.Scope.resolveName(Scope.java:56)
	at org.arend.naming.scope.LexicalScope.resolveInternal(LexicalScope.java:191)
	at org.arend.naming.scope.LexicalScope.resolve(LexicalScope.java:271)
	at org.arend.naming.scope.LexicalScope.resolveName(LexicalScope.java:323)
	at org.arend.naming.scope.LexicalScope.resolve(LexicalScope.java:317)
	at org.arend.naming.scope.LexicalScope.resolveName(LexicalScope.java:323)
	at org.arend.psi.ext.ArendCompositeElementKt$getArendScope$2.resolveName(ArendCompositeElement.kt:73)
	at org.arend.resolving.ArendReferenceBase$resolve$resolver$1.invoke(ArendReference.kt:74)
	at org.arend.resolving.ArendReferenceBase$resolve$resolver$1.invoke(ArendReference.kt:47)
	at org.arend.resolving.ArendResolveCache.resolveCached(ArendResolveCache.kt:44)
	at org.arend.resolving.ArendReferenceBase.resolve(ArendReference.kt:79)
	at org.arend.psi.ext.ArendDefClass.getSuperClassReferences(ArendDefClass.kt:55)
	at org.arend.naming.scope.ClassFieldImplScope.find(ClassFieldImplScope.java:76)
	at org.arend.naming.scope.Scope.resolveName(Scope.java:51)
	at org.arend.naming.scope.Scope.resolveName(Scope.java:56)
	at org.arend.naming.scope.LexicalScope.resolveInternal(LexicalScope.java:191)
	at org.arend.naming.scope.LexicalScope.resolve(LexicalScope.java:271)
	at org.arend.naming.scope.LexicalScope.resolveName(LexicalScope.java:323)
	at org.arend.naming.scope.LexicalScope.resolve(LexicalScope.java:317)
	at org.arend.naming.scope.LexicalScope.resolveName(LexicalScope.java:323)
	at org.arend.psi.ext.ArendCompositeElementKt$getArendScope$2.resolveName(ArendCompositeElement.kt:73)
	at org.arend.resolving.ArendReferenceBase$resolve$resolver$1.invoke(ArendReference.kt:74)
	at org.arend.resolving.ArendReferenceBase$resolve$resolver$1.invoke(ArendReference.kt:47)
	at org.arend.resolving.ArendResolveCache.resolveCached(ArendResolveCache.kt:44)
	at org.arend.resolving.ArendReferenceBase.resolve(ArendReference.kt:79)
	at org.arend.psi.ext.ArendDefClass.getSuperClassReferences(ArendDefClass.kt:55)
	at org.arend.naming.scope.ClassFieldImplScope.find(ClassFieldImplScope.java:76)
	at org.arend.naming.scope.Scope.resolveName(Scope.java:51)
	at org.arend.naming.scope.Scope.resolveName(Scope.java:56)
	at org.arend.naming.scope.LexicalScope.resolveInternal(LexicalScope.java:191)
	at org.arend.naming.scope.LexicalScope.resolve(LexicalScope.java:271)
	at org.arend.naming.scope.LexicalScope.resolveName(LexicalScope.java:323)
	at org.arend.naming.scope.LexicalScope.resolve(LexicalScope.java:317)
	at org.arend.naming.scope.LexicalScope.resolveName(LexicalScope.java:323)
```

**Comment by valis** [comment]
How to reproduce this?

**Comment by sxhya** [comment]
> How to reproduce this?

I've added code (not minimized) into soe_reproducer branch of arend-lib.

**Comment by sxhya** [comment]
Re-reported as https://github.com/JetBrains/Arend/issues/341
