### ISSUE TITLE
Exception on 1st open of arend-lib

### ISSUE THREAD

**Issue by sxhya** [JetBrains/intellij-arend#422]
I've thoroughly cleaned everything in `intellij-arend` and `arend-lib` and got this exception on 1st open of `arend-lib`.

```
 java.lang.RuntimeException: Cannot invoke (class=LegacyProjectModelListenersBridge, method=changed, topic=WorkspaceModelChangeListener)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:676)
	at com.intellij.util.messages.impl.MessageBusImplKt.executeOrAddToQueue(MessageBusImpl.kt:491)
	at com.intellij.util.messages.impl.MessagePublisher.publish$intellij_platform_core(MessageBusImpl.kt:471)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:448)
	at jdk.proxy2/jdk.proxy2.$Proxy102.changed(Unknown Source)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl$onChanged$3.invoke(WorkspaceModelImpl.kt:347)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl$onChanged$3.invoke(WorkspaceModelImpl.kt:346)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.logErrorOnEventHandling(WorkspaceModelImpl.kt:392)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.onChanged(WorkspaceModelImpl.kt:346)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.access$onChanged(WorkspaceModelImpl.kt:36)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl$updateProjectModel$generalTime$1$7.invoke(WorkspaceModelImpl.kt:161)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl$updateProjectModel$generalTime$1$7.invoke(WorkspaceModelImpl.kt:161)
	at com.intellij.platform.workspace.storage.impl.VersionedEntityStorageImpl.replace(VersionedEntityStorageImpl.kt:190)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.updateProjectModel(WorkspaceModelImpl.kt:161)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModifiableModuleModelBridgeImpl.commit(ModifiableModuleModelBridgeImpl.kt:248)
	at com.intellij.ide.util.projectWizard.importSources.impl.ProjectFromSourcesBuilderImpl.lambda$doCommit$3(ProjectFromSourcesBuilderImpl.java:277)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:980)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1006)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:86)
	at com.intellij.ide.util.projectWizard.importSources.impl.ProjectFromSourcesBuilderImpl.doCommit(ProjectFromSourcesBuilderImpl.java:274)
	at com.intellij.ide.util.projectWizard.importSources.impl.ProjectFromSourcesBuilderImpl.commit(ProjectFromSourcesBuilderImpl.java:308)
	at com.intellij.ide.util.projectWizard.importSources.impl.ProjectFromSourcesBuilderImpl.commit(ProjectFromSourcesBuilderImpl.java:316)
	at org.arend.project.ArendProjectImportBuilder.commit(ArendProjectImportBuilder.kt:37)
	at com.intellij.projectImport.ProjectImportBuilder.commit(ProjectImportBuilder.java:50)
	at org.arend.project.ArendProjectOpenProcessor.importProjectAfterwards(ArendProjectOpenProcessor.kt:43)
	at org.arend.project.ArendProjectOpenProcessor$doOpenProject$1$1$1.invoke(ArendProjectOpenProcessor.kt:31)
	at org.arend.project.ArendProjectOpenProcessor$doOpenProject$1$1$1.invoke(ArendProjectOpenProcessor.kt:31)
	at com.intellij.openapi.application.ActionsKt.invokeLater$lambda$5(actions.kt:74)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.RuntimeException: Cannot invoke (class=, method=modulesAdded, topic=ModuleListener)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:676)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:422)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:401)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:460)
	at jdk.proxy2/jdk.proxy2.$Proxy117.modulesAdded(Unknown Source)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModuleManagerBridgeImpl$Companion.fireModulesAdded(ModuleManagerBridgeImpl.kt:504)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.LegacyProjectModelListenersBridge.fireModuleAddedInWriteAction$lambda$5(LegacyProjectModelListenersBridge.kt:193)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:992)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.LegacyProjectModelListenersBridge.fireModuleAddedInWriteAction(LegacyProjectModelListenersBridge.kt:184)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.LegacyProjectModelListenersBridge.processModuleChange(LegacyProjectModelListenersBridge.kt:116)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.LegacyProjectModelListenersBridge.changed(LegacyProjectModelListenersBridge.kt:69)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:699)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:663)
	... 66 more
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "def" is null
	at org.arend.module.serialization.CallTargetProvider.getCallTarget(CallTargetProvider.java:16)
	at org.arend.module.serialization.ExpressionDeserialization.readDataCall(ExpressionDeserialization.java:406)
	at org.arend.module.serialization.ExpressionDeserialization.readExpr(ExpressionDeserialization.java:309)
	at org.arend.module.serialization.DefinitionDeserialization.readBody(DefinitionDeserialization.java:410)
	at org.arend.module.serialization.DefinitionDeserialization.fillInFunctionDefinition(DefinitionDeserialization.java:470)
	at org.arend.module.serialization.DefinitionDeserialization.fillInDefinition(DefinitionDeserialization.java:47)
	at org.arend.module.serialization.ModuleDeserialization.readModule(ModuleDeserialization.java:65)
	at org.arend.source.StreamBinarySource.load(StreamBinarySource.java:137)
	at org.arend.source.SourceLoader.fillInBinary(SourceLoader.java:195)
	at org.arend.source.StreamBinarySource.load(StreamBinarySource.java:128)
	at org.arend.source.SourceLoader.fillInBinary(SourceLoader.java:195)
	at org.arend.source.SourceLoader.loadBinary(SourceLoader.java:187)
	at org.arend.library.SourceLibrary.load(SourceLibrary.java:301)
	at org.arend.library.LibraryManager.loadLibrary(LibraryManager.java:224)
	at org.arend.util.ProjectUtilsKt$register$1.invoke(ProjectUtils.kt:63)
	at org.arend.util.ProjectUtilsKt$register$1.invoke(ProjectUtils.kt:62)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:31)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:31)
	at org.arend.util.ProjectUtilsKt.register(ProjectUtils.kt:62)
	at org.arend.ArendStartupActivity$execute$2.modulesAdded(ArendStartupActivity.kt:31)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:699)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:663)
	... 79 more
```

**Comment by sxhya** [comment]
Duplicate
