### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by s3midetnov** [JetBrains/intellij-arend#462]
java.lang.NoSuchMethodError: 'java.util.Set org.arend.ext.core.definition.CoreClassDefinition.getFields()'
	at org.arend.lib.util.Utils.getNotImplementedField(Utils.java:315)
	at org.arend.lib.meta.ExtMeta$ExtGenerator.generate(ExtMeta.java:210)
	at org.arend.lib.meta.ExtMeta$1.invokeMeta(ExtMeta.java:811)
	at org.arend.typechecking.visitor.CheckTypeVisitor.invokeMeta(CheckTypeVisitor.java:3113)
	at org.arend.typechecking.visitor.CheckTypeVisitor.checkMeta(CheckTypeVisitor.java:3177)
	at org.arend.typechecking.visitor.CheckTypeVisitor.visitReference(CheckTypeVisitor.java:1974)
	at org.arend.typechecking.visitor.CheckTypeVisitor.visitReference(CheckTypeVisitor.java:1969)
	at org.arend.typechecking.visitor.CheckTypeVisitor.visitReference(CheckTypeVisitor.java:88)
	at org.arend.term.concrete.Concrete$ReferenceExpression.accept(Concrete.java:666)
	at org.arend.typechecking.visitor.CheckTypeVisitor.checkExpr(CheckTypeVisitor.java:957)
	at org.arend.typechecking.visitor.CheckTypeVisitor.visitLam(CheckTypeVisitor.java:2359)
	at org.arend.typechecking.visitor.CheckTypeVisitor.lambda$visitLam$1(CheckTypeVisitor.java:2438)
	at org.arend.typechecking.visitor.CheckTypeVisitor.visitLam(CheckTypeVisitor.java:2520)
	at org.arend.typechecking.visitor.CheckTypeVisitor.visitLam(CheckTypeVisitor.java:2554)
	at org.arend.typechecking.visitor.CheckTypeVisitor.visitLam(CheckTypeVisitor.java:88)
	at org.arend.term.concrete.Concrete$LamExpression.accept(Concrete.java:1047)
	at org.arend.typechecking.visitor.CheckTypeVisitor.checkExpr(CheckTypeVisitor.java:957)
	at org.arend.typechecking.visitor.CheckTypeVisitor.checkArgument(CheckTypeVisitor.java:1206)
	at org.arend.typechecking.implicitargs.StdImplicitArgsInference.inferArg(StdImplicitArgsInference.java:181)
	at org.arend.typechecking.implicitargs.StdImplicitArgsInference.infer(StdImplicitArgsInference.java:721)
	at org.arend.typechecking.visitor.CheckTypeVisitor.visitApp(CheckTypeVisitor.java:3349)
	at org.arend.typechecking.visitor.CheckTypeVisitor.visitApp(CheckTypeVisitor.java:3297)
	at org.arend.typechecking.visitor.CheckTypeVisitor.visitApp(CheckTypeVisitor.java:88)
	at org.arend.term.concrete.Concrete$AppExpression.accept(Concrete.java:477)
	at org.arend.typechecking.visitor.CheckTypeVisitor.checkExpr(CheckTypeVisitor.java:957)
	at org.arend.typechecking.visitor.CheckTypeVisitor.typecheck(CheckTypeVisitor.java:562)
	at org.arend.typechecking.visitor.CheckTypeVisitor.typecheck(CheckTypeVisitor.java:88)
	at org.arend.lib.meta.ExtMeta.invokeMeta(ExtMeta.java:807)
	at org.arend.ext.typechecking.MetaDefinition.checkAndInvokeMeta(MetaDefinition.java:60)
	at org.arend.ext.typechecking.DeferredMetaDefinition.invokeMeta(DeferredMetaDefinition.java:67)
	at org.arend.typechecking.visitor.CheckTypeVisitor.invokeMeta(CheckTypeVisitor.java:3113)
	at org.arend.typechecking.visitor.CheckTypeVisitor.checkMeta(CheckTypeVisitor.java:3177)
	at org.arend.typechecking.visitor.CheckTypeVisitor.visitApp(CheckTypeVisitor.java:3313)
	at org.arend.typechecking.visitor.CheckTypeVisitor.visitApp(CheckTypeVisitor.java:3297)
	at org.arend.typechecking.visitor.CheckTypeVisitor.visitApp(CheckTypeVisitor.java:88)
	at org.arend.term.concrete.Concrete$AppExpression.accept(Concrete.java:477)
	at org.arend.typechecking.visitor.CheckTypeVisitor.checkExpr(CheckTypeVisitor.java:957)
	at org.arend.typechecking.visitor.DefinitionTypechecker.typecheckFunctionBody(DefinitionTypechecker.java:1661)
	at org.arend.typechecking.visitor.DefinitionTypechecker.visitFunction(DefinitionTypechecker.java:173)
	at org.arend.typechecking.visitor.DefinitionTypechecker.visitFunction(DefinitionTypechecker.java:64)
	at org.arend.term.concrete.Concrete$BaseFunctionDefinition.accept(Concrete.java:2548)
	at org.arend.term.concrete.Concrete$Definition.accept(Concrete.java:2097)
	at org.arend.typechecking.order.listener.TypecheckingOrderingListener.unitFound(TypecheckingOrderingListener.java:243)
	at org.arend.typechecking.order.Ordering.unitFound(Ordering.java:189)
	at org.arend.typechecking.order.Ordering.unitFound(Ordering.java:24)
	at org.arend.typechecking.order.TarjanSCC.doOrderRecursively(TarjanSCC.java:54)
	at org.arend.typechecking.order.TarjanSCC.lambda$doOrderRecursively$0(TarjanSCC.java:37)
	at org.arend.typechecking.order.Ordering.forDependencies(Ordering.java:178)
	at org.arend.typechecking.order.Ordering.forDependencies(Ordering.java:24)
	at org.arend.typechecking.order.TarjanSCC.doOrderRecursively(TarjanSCC.java:34)
	at org.arend.typechecking.order.TarjanSCC.order(TarjanSCC.java:24)
	at org.arend.typechecking.order.Ordering.order(Ordering.java:120)
	at org.arend.typechecking.order.Ordering.sccFound(Ordering.java:293)
	at org.arend.typechecking.order.TarjanSCC.doOrderRecursively(TarjanSCC.java:57)
	at org.arend.typechecking.order.TarjanSCC.order(TarjanSCC.java:24)
	at org.arend.typechecking.order.Ordering.order(Ordering.java:120)
	at org.arend.typechecking.order.listener.TypecheckingOrderingListener.lambda$typecheckDefinitions$0(TypecheckingOrderingListener.java:108)
	at org.arend.typechecking.computation.ComputationRunner.run(ComputationRunner.java:48)
	at org.arend.typechecking.computation.BooleanComputationRunner.run(BooleanComputationRunner.java:8)
	at org.arend.typechecking.order.listener.TypecheckingOrderingListener.typecheckDefinitions(TypecheckingOrderingListener.java:105)
	at org.arend.extImpl.ArendDependencyProviderImpl.getDefinition(ArendDependencyProviderImpl.java:56)
	at org.arend.extImpl.ArendDependencyProviderImpl.load(ArendDependencyProviderImpl.java:75)
	at org.arend.lib.StdExtension.load(StdExtension.java:118)
	at org.arend.library.SourceLibrary.load(SourceLibrary.java:309)
	at org.arend.library.LibraryManager.loadLibrary(LibraryManager.java:224)
	at org.arend.util.ProjectUtilsKt$register$1.invoke(ProjectUtils.kt:71)
	at org.arend.util.ProjectUtilsKt$register$1.invoke(ProjectUtils.kt:70)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:31)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:894)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:31)
	at org.arend.util.ProjectUtilsKt.register(ProjectUtils.kt:70)
	at org.arend.ArendStartupActivity$execute$3.performInDumbMode$lambda$0(ArendStartupActivity.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by sxhya** [comment]
Are you sure that the version of Arend console app corresponds to the version of arend-lib/meta? Can this behavior be reproduced after both are consecutively rebuilt?
