### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by demiurg906** [JetBrains/intellij-arend#49]
Latest version of plugin throws exception during project initialization. After that imports not working (`unresolved reference` on every `\import smth`)

```
java.lang.AssertionError
	at org.arend.core.context.param.UntypedDependentLink.<init>(UntypedDependentLink.java:15)
	at org.arend.module.serialization.ExpressionDeserialization.readParameter(ExpressionDeserialization.java:153)
	at org.arend.module.serialization.DefinitionDeserialization.readPattern(DefinitionDeserialization.java:272)
	at org.arend.module.serialization.DefinitionDeserialization.readPatterns(DefinitionDeserialization.java:264)
	at org.arend.module.serialization.DefinitionDeserialization.fillInDataDefinition(DefinitionDeserialization.java:173)
	at org.arend.module.serialization.DefinitionDeserialization.fillInDefinition(DefinitionDeserialization.java:48)
	at org.arend.module.serialization.ModuleDeserialization.readModule(ModuleDeserialization.java:50)
	at org.arend.source.StreamBinarySource.load(StreamBinarySource.java:115)
	at org.arend.source.SourceLoader.fillInBinary(SourceLoader.java:92)
	at org.arend.source.StreamBinarySource.load(StreamBinarySource.java:106)
	at org.arend.source.SourceLoader.fillInBinary(SourceLoader.java:92)
	at org.arend.source.SourceLoader.loadBinary(SourceLoader.java:87)
	at org.arend.library.SourceLibrary.load(SourceLibrary.java:160)
	at org.arend.module.ArendRawLibrary.load(ArendRawLibrary.kt:36)
	at org.arend.library.LibraryManager.loadLibrary(LibraryManager.java:157)
	at org.arend.ArendStartupActivity.runActivity(ArendStartupActivity.kt:32)
```

**Comment by valis** [comment]
Fixed in [a8e99ff](https://github.com/JetBrains/Arend/commit/a8e99ff948745035bafa9c72bc36bc4cfe0a6a2c).
